Liteweb\EventLogPlugin\Entity\EventLog:
  type: entity
  table: liteweb_event_log_new
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    occurred_at:
      type: datetime

    entity_type:
      type: string

      entity_id:
        type: string

    payload:
      type: json_array

    actor:
      type: string

    user_context:
      type: string
      nullable: true

    user_context_id:
      type: string
      nullable: true

    url:
      type: string
      nullable: true

